name: Web CI

on:
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/**"
      - ".nvmrc"
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/**"
      - ".nvmrc"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    env:
      GENERATE_SOURCEMAP: "false"
      REACT_APP_ALCHEMY_KEY: ""
      REACT_APP_WALLET_CONNECT_PROJECT_ID: ""
      REACT_APP_ROCKET_SWEEP_URL: "https://rocketsweep.vercel.app"
      REACT_APP_ROUTER: "browser"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: web/package-lock.json

      - run: npm ci
      - run: npm run build:ci
      - run: npm run test:ci
